openapi: 3.0.0
info:
  description: >-
    This is a definition of Permissions API which is a part of an architecture for delivering dataset permissions on ELIXIR AAI. The whole architecture is explained at: https://docs.google.com/document/d/1rqCD75HRA99HKwq0s-OkWWBKiaEo2JO-_MYjlsyiSQ4
    
    This API utilises the GA4GH RI data model: https://docs.google.com/document/d/11Wg-uL75ypU5eNu2p_xh9gspmbGtmLzmdq5VfPHBirE

  version: "2.0"
  title: Permissions API
  contact:
    email: teemu.kataja@csc.fi
  license:
    name: License Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Common Permissions Endpoint
    description: Common endpoint for retrieving Permissions from any kind of Authorising service to ELIXIR AAI.

paths:

  /permissions/{elixirId}:
    get:
      tags:
        - Common Permissions Endpoint
      summary: Retrieve datasets user has been authorised to access.
      description: Authentication at EGA with `HTTP Basic`. Authentication at REMS with `Permissions-Api-Key`.
      parameters:
      - name: elixirId
        in: path
        description: The user's ELIXIR AAI issued identifier.
        required: true
        schema:
          type: string
      security:
        - BasicAuth: []
        - ApiKeyAuth: []
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionsResponse'
        400:
          description: Username not provided
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: User not found

components:

  schemas:

    PermissionsResponse:
      description: The `application/json` response given from the permissions endpoint.
      properties:
        ga4ghSignature:
          type: string
          format: SHA256
          description: A checksum hash for the `ga4gh` object.
          example: c01b39c7a35ccc3b081a3e83d2c71fa9a767ebfeb45c69f08e17dfe3ef375a7b
        ga4gh:
          $ref: '#/components/schemas/ga4gh'

    ga4gh:
      type: object
      description: GA4GH RI Claims data model.
      properties:
        ControlledAccessGrants:
          $ref: '#/components/schemas/ControlledAccessGrants'
     
    ControlledAccessGrants:
      type: array
      description: An array of permitted resources.
      items:
        $ref: '#/components/schemas/ControlledAccessGrantsObject' 

    ControlledAccessGrantsObject:
      type: object
      description: User affiliations and roles.
      properties:
        value:
          type: string
          description: URL comprised of dataset uuid prepended with dataset location.
          example: https://www.ebi.ac.uk/ega/EGAD000000000001
        source:
          type: string
          description: URL comprised of DAC uuid prepended with DAC info address. Defaults to https://ga4gh.org/duri/no_org if DAC is not an organisation.
          example: https://ega-archive.org/dacs/EGAC00000000001
        by:
          type: string
          description: A static value.
          example: dac
        authoriser:
          type: string
          format: email
          description: The person who authorised this permission
          example: john.doe@dac.org
        asserted:
          type: integer
          description: Start date of this affiliation in Unix time (no milliseconds).
          example: 1546300800
        expires:
          type: integer
          description: End date of this affiliation in Unix time (no milliseconds).
          example: 1577836800

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Permissions-Api-Key 

externalDocs:
  url: https://app.swaggerhub.com/apis/ELIXIR-Finland/Permissions/1.2
  description: ELIXIR Permissions API 1.2
